Currency_Converter/Models/CurrencyConverter.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Currency_Converter.Models
{
    public class CurrencyConverter
    {
        public float a;
        public float b;
        public object result;

        public CurrencyConverter(float a, float b)
        {
            this.a = a;
            this.b = b;
        }

        public void mul()
        {
            result = a * b;
        }
    }
}

Currency_Converter/Models/ErrorViewModel.cs
using System;

namespace Currency_Converter.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Currency_Converter/Controllers/CurrencyConverterController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Currency_Converter.Controllers
{
    public class CurrencyConverterController : Controller
    {
        public IActionResult Index(float a, float b)
        {
            Models.CurrencyConverter res = new Models.CurrencyConverter(a, b);
            res.mul();

            return View("currencyConverterView", res);
        }
    }
}

Currency_Converter/Controllers/HomeController.cs
using Currency_Converter.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace Currency_Converter.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Currency_Converter/Views/CurrencyConverter/currencyConverterView.cshtml
@{
    ViewData["Title"] = "currencyConverterView";
}

<div class="cal">
    <h1 class="cal-header">Currency Converter</h1>

    <form class="cal-form" action="/CurrencyConverter" method="get">
        <div class="field-group">
            <span class="label">Số tiền ($)</span>
            <input type="text" name="a" value="@Model.a" /> <br />
        </div>

        <div class="field-group">
            <span class="label">tỉ giá</span>
            <input type="text" name="b" value="@Model.b" /> <br />
        </div>

        <input type="submit" value="Tính" class="cal-btn" />
        <p>
            <span class="label">Kết quả:</span>
            @if (Model != null)
            {
                @Model.result
            }
            <span class="unit">(VNĐ)</span>
        </p>
    </form>
</div>

Currency_Converter/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Currency_Converter/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Currency_Converter</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="CurrencyConverter" asp-action="">Currency_Converter</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - Currency_Converter - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>